version: "3.7"

services:
  sample:
    container_name: ci_build_test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8320:8320"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
