apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: junisduck/image_test:jun-junisduck-test-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8319
      restartPolicy: Always
