apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    app: react-app
spec:
  selector:
    app: react-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
#    nodePort: 31000
