apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - port: 8318
    targetPort: 8318
    protocol: TCP
