  #apiVersion: networking.k8s.io/v1
  #kind: Ingress
apiVersion: v1
kind: Service
metadata:
  name: jun-nginx-ingress
  namespace: nginx-app
    #annotations:
      #nginx.ingress.kubernetes.io/rewrite-target: /$1
      #kubernetes.io/ingress.class: "nginx" # 사용할 Ingress Controller
  labels:
    app: nginx-app
spec:
  rules:
  - http:
      paths:
        - path: /nginx
          pathType: Prefix
          backend:
            service:
              name: jun-nginx-ingress
              port:
                number: 8318
