# https://docs.docker.com/build/ci/github-actions/#step-three-define-the-workflow-steps

# workflow 이름
name: Docker hub image build
# workflow에서 작업이 실행되는 조건 (push, pull, ...)
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
# 작업에 대한 정의
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ### repository check
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: junisduck/image_test
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      ### docker login, docker hub 자격 증명
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      ### setup docker buildx
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      ### build and push docker image
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          load: true
            #push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      ### slack notification
      -
        name: Slack Notification Demo
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          author_name: dev(?)
          fields: repo,commit,message,author
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
